server:
  port: 8080
  error:
    path: /error
    whitelabel:
      enabled: false
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_menu
    username: postgres
    password: rootroot1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    show-sql: true

application:
  security:
    jwt:
      secret-key: cUEmhf7z62fwiGxpnUh4SlDyERzZ7KDO
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days