server:
  port: 8080
  error:
    path: /error
    whitelabel:
      enabled: false
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_menu
    username: postgres
    password: ItsMyLife0203
#    password: rootroot1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    show-sql: true

#это может пригодится для ручного кодировщика
jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEV8X43g
      iteration: 64
      keylength: 256

#debug: true
